### ISSUE TITLE
[UI 개선] 가로스크롤 제거 후, 줄나눔 추가

### ISSUE THREAD

**Issue by JangHyunjeong** [JeongbinYoon/todo#1]
https://github.com/JeongbinYoon/todo/blob/d3146a6ef2d5531edfe4dbd2bca0565e266a558b/src/components/todo-list/Task.tsx#L95

가로 스크롤을 만드는 것 보다 아래와 같이 내용이 넘치면 줄나눔이 되는 방식으로 처리하는면 
UI가 더 깔끔해 보일것 같습니다! 

![정빈님](https://github.com/user-attachments/assets/3b26e5c9-0702-4ce8-befa-6e22d65b99ba)

**Comment by JeongbinYoon** [comment]
반영했습니다!
