### ISSUE TITLE
[UI/UX] List 영역 가로 스크롤 제거

### ISSUE THREAD

**Issue by yoohyunju** [JeongbinYoon/todo#3]
### 칭찬할 점
UI 심플하고 좋네요
타입스크립트도 슥샥쇽 적용하시고...😮 멋지십니다.

### 개선할 점
할일 목록 영역에 가로 스크롤은 현재 불필요해 보여서 추후 제거하면 좋을 것 같습니다!

**Comment by JeongbinYoon** [comment]
mac에서 보이지 않아 몰랐는데 피드백 감사합니다. 
반영 했습니다!
