### ISSUE TITLE
[ UI/UX 개선 ] 할일 목록간 구분 

### ISSUE THREAD

**Issue by ydw1996** [JeongbinYoon/todo#4]
![Frame 32@2x](https://github.com/user-attachments/assets/7c188e33-64a2-466c-9915-918828076697)

그리고 역시 코드는 깔끔하게 보기 좋슴다 앞으로 더 기대할게요!

**Comment by JeongbinYoon** [comment]
꼼꼼한 피드백 감사합니다. 
반영했습니다!
