### ISSUE TITLE
[제안] import

### ISSUE THREAD

**Issue by hansololiviakim** [JeongbinYoon/todo#5]
바쁘신 와중에 서버까지 연결해두셔서 깜짝 놀랐습니다😳 그리고 초기 버전 디자인도 너무 깔끔해서 좋았어요!

이건 제가 어떻게 코드를 짜는지에 관한 의견이라서 참고해주시면 좋을 것 같아요ㅎㅎ 만약 지금처럼 List 안에 동일 경로 컴포넌트들을 import 해오는 형식이라면 저는 import 해오는 컴포넌트들을 한 뎁스 더 넣어서 import {~, ~} from ~ 으로 가져올 것 같아요!

저는 index.js로 묶는걸 중요하게 생각하는 편이기 때문입니다.. 같은 경로에 있는 파일인지 시각적으로 구분도 편하고 컴포넌트 추가/삭제할 때도 경로 다 안적고 쉽게 관리할 수 있구요!

덧붙여서 index.js 작성할 때도 새 컴포넌트라고 맨 아래 넣지 않고 무조건 이름순으로 정렬해서 추가합니다.. 순서는 어차피 파일 만들었을 때 폴더구조에서 이름순 어떻게 되어있는지 나와있기 때문에 그 순서대로 하면 되니까요! 파일 경로 찾을 때도 순서대로 보여서 편해요👍 진짜 사소하고 귀찮은 일이지만 몇 초의 귀찮음으로 모두의 유지보수성과 가독성이 올라간다면 저는 마땅히 그래야 한다는게 개인적인 신념이구요.. 캐스퍼도 인덱스 엄청 정리해뒀습니다ㅎㅎ

추가적으로 리액트 쿼리 > 탠스택 쿼리로 버전업 되면서 useQuery나 useMutation 호출하는 방법이 살짝! 달라졌는데 이미 알고 계실수도 있지만 한 번 정리해보셔도 좋을 것 같아요~! 저는 탠스택 처음 쓸 때 살짝 헷갈렸거든요🙂‍↕️

멋진 코드 잘 봤습니다!

**Comment by JeongbinYoon** [comment]
import 관련해서는 잘 신경쓰지 않았었는데 의견보고 정리해봤습니다.
캐스퍼에서도 많이 봤었는데 확실히 프로젝트가 커질수록 정리가 중요해지는 것 같습니다. 많은 컴포넌트를 포함하면서  import문만해도 굉장히 길었었는데 간결하게 정리된 걸 봤습니다.
한솔님 덕분에 유지보수에 용이한 정리 방법 얻어 갑니다. 감사합니다.
리액트 쿼리를 너무 오랜만에 써봐서 아직 익숙하지 않네요. 앞으로 프로젝트  더 진행하면서 탠스택 쿼리도 조금씩 써보겠습니다
소중한 의견 감사합니다~
